apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.web.name }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: {{ .Values.web.host }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.web.name }}
              servicePort: http
