apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
  labels:
    {{ template "mychart.chart" . }}
    app: {{ .Values.web.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.name }}
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: {{ .Values.web.name }}
          image: {{ .Values.web.image }}
          ports:
            - containerPort: 80
