name: CI
on:
  push:
    branches-ignore:
      - 'test-githubactions'
      - 'fuga'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_AUTH}}
          IMAGE: gcr.io/test-tool-257606/build-app
        with:
          args: helm init --service-account tiller --wait --upgrade && \
            helm upgrade --install --set web.name="app-${GITHUB_REF}-${GITHUB_SHA}" --set web.image="${IMAGE}" --set web.host="${GITHUB_REF}-${GITHUB_SHA}-test2l.com" --wait --force app-${GITHUB_REF}-${GITHUB_SHA} ./mychart
