name: CI2
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: docker://devth/helm:latest
        env:
          IMAGE: gcr.io/test-tool-257606/build-app
        with:
          args: /bin/sh -c 'echo hoge && ls && echo fuga'
