name: CI2
on:
  push:
    branches-ignore:
      - 'test-githubactions'
      - 'hoge'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Deploy app
        uses: docker://devth/helm:latest
        env:
          IMAGE: gcr.io/test-tool-257606/build-app
          GCLOUD_AUTH: ${{secrets.GCLOUD_AUTH}}
        with:
          entrypoint: /bin/bash
          args: -c "
            mkdir -p /etc/deploy &&
            echo $GCLOUD_AUTH | base64 -d > /etc/deploy/sa.json &&
            gcloud auth activate-service-account --key-file=/etc/deploy/sa.json --project=${{secrets.GCLOUD_PROJECT_ID}} &&
            gcloud container clusters get-credentials ${{secrets.GCLOUD_CLUSTER_NAME}} --zone ${{secrets.GCLOUD_ZONE}} --project ${{secrets.GCLOUD_PROJECT_ID}} &&
            helm init --service-account tiller --wait --upgrade &&
            helm upgrade --install --set web.name="app-$GITHUB_SHA" --set web.image="$IMAGE" --set web.host="${{steps.extract_branch.outputs.branch}}-test2l.com" --wait --force app-$GITHUB_SHA ./mychart
            "
